export const EMPTY_STATE_ICONS = {
  deadlines: "⏰",
  meetings: "📅",
  subscriptions: "🔄",
};

export const UI_TEXT = {
  en: {
    loadingKicker: "Loading",
    loadingTitle: "Loading run artifacts...",
    frontendKicker: "Frontend",
    loadErrorTitle: "Could not load saved runs",
    noDataKicker: "No data yet",
    noDataTitle: "Run the email agent first",
    noDataBody: "Saved summaries from data/runs/ will appear here automatically.",
    runAgent: "Run agent",
    runAgentTitle: "Create a fresh summary",
    runAgentHint: "Choose a provider and date to generate an updated summary from your inbox.",
    runNow: "Create summary",
    runningRun: "Creating summary...",
    runCompleted: (date) => `Summary run completed for ${date}.`,
    runProvider: "Run with",
    runDate: "Run date",
    interfaceLanguage: "Interface",
    briefMode: "Overview",
    inspectMode: "Inspection",
    inspectTitle: "Deep inspection",
    openInspectMode: "Open inspect mode",
    briefHeadline: "Your day in email",
    currentRun: "Current summary",
    newRun: "New summary",
    launchHint: "Choose a provider and date, then create a fresh summary.",
    signalLabel: "Daily summary",
    runOverview: "Overview",
    close: "Close",
    hideDetails: "Hide details",
    showDetails: "Show details",
    savedRun: "Shown summary",
    inspector: "Inspector",
    technicalMetadata: "Technical metadata",
    inspectorPreview: "Open details for the full technical trace behind this run.",
    provider: "Provider",
    language: "Language",
    llm: "LLM",
    execution: "Execution",
    startedAt: "Started",
    completedAt: "Completed",
    workflowDuration: "Workflow duration",
    inputTokens: "Input tokens",
    outputTokens: "Output tokens",
    totalTokens: "Total tokens",
    estimatedCost: "Estimated cost",
    emailCount: "Email count",
    emailCountFound: (count) => `${count} emails found for this day`,
    importantCount: "Important count",
    llmClassification: "LLM classification",
    llmSummary: "LLM summary",
    classificationRoute: "Classification route",
    summaryRoute: "Summary route",
    lowConfidenceItems: "Low-confidence items",
    abstainedItems: "Abstained items",
    llmFallbacks: "LLM fallbacks",
    inboxFocus: "Inbox focus",
    importantMessages: "Important messages",
    noImportantMessages: "No important emails were identified for this summary.",
    actionBoard: "Action board",
    nextSteps: "Next steps",
    noFollowup: "No follow-up actions were extracted for this summary.",
    deadlines: "Deadlines",
    timeSensitiveItems: "What needs attention soon",
    noDeadlines: "No upcoming deadlines or urgent items were found for this summary.",
    meetings: "Meetings",
    calendarSignals: "Meetings and invites",
    noMeetings: "No meetings or invitations were found.",
    subscriptions: "Subscriptions",
    recurringCharges: "Recurring charges",
    noSubscriptions: "No likely recurring subscriptions were extracted for this summary.",
    workflow: "Workflow",
    systemPath: "System path",
    hide: "Hide",
    view: "View",
    workflowSummary: "A compact system overview is available when you want to inspect the workflow path.",
    stepTimingSummary: "Each saved run now includes timestamps and step durations for a clearer operational trace.",
    stepCompletedInDetail: (duration) => `Completed in ${duration}.`,
    usageRecordedDetail: (tokens, cost) =>
      tokens > 0 ? `${tokens} total LLM tokens recorded. Estimated cost ${cost}.` : "No LLM token usage recorded for this run.",
    whyThisMatters: "Why this matters",
    projectValue: "Project value",
    projectSummary: "The interface is intentionally product-first, while the engineering story stays available on demand.",
    projectBullet1: "Real Gmail runs and saved artifacts already drive the interface.",
    projectBullet2: "The product view stays clean while technical metadata remains accessible on demand.",
    projectBullet3: "The next step could be a lightweight API or live refresh after each summary run.",
    importantMails: "Important mails",
    subscriptionsStat: "Subscriptions",
    deadlinesStat: "Deadlines",
    meetingsStat: "Meetings",
    german: "German",
    english: "English",
    unknown: "Unknown",
    yes: "Yes",
    no: "No",
    gmailLabel: "gmail",
    mockLabel: "mock",
    webdeLabel: "web.de",
    noPreview: "No preview available.",
    savedSummary: "Saved summary",
    structuredExtraction: "Structured extraction",
    artifactBackedUi: "Artifact-backed UI",
    guardrails: "Guardrails",
    nextStep: "Next step",
    savedSummaryDetail: (date, count) => `Loaded summary.json for ${date} with ${count} important emails.`,
    structuredExtractionDetail: (deadlines, meetings, subscriptions) =>
      `Saved ${deadlines} deadline signals, ${meetings} meeting signals, and ${subscriptions} subscription signals as first-class artifacts.`,
    artifactBackedUiDetail: "This dashboard reflects real persisted outputs from the Python workflow.",
    guardrailsDetail: (fallbacks, abstained) =>
      fallbacks > 0
        ? `Guardrails replaced ${fallbacks} low-confidence classifications and tracked ${abstained} abstentions.`
        : "No low-confidence classifications needed fallback in this run.",
    nextStepDetail: "Add token, cost, and latency telemetry to the saved run metadata.",
    guardrailsBrief: (count) =>
      `Guardrails replaced ${count} low-confidence classifications with safer fallback logic.`,
    likelyRecurringFallback: "Likely recurring subscription signal detected.",
    noMeetingDetails: "No additional meeting details extracted.",
    responseLikelyNeeded: "Response likely needed",
    noDueHint: "No explicit due hint found.",
    allEmails: "All emails",
    runInbox: "View emails",
    inspectEveryEmail: "View every email captured in this summary, including informational and lower-priority messages.",
    openAllEmails: "Open all emails",
    emailDetail: "Email detail",
    emailList: "Emails",
    openEmail: "Open email",
    receivedAt: "Received",
    subject: "Subject",
    senderLabel: "Sender",
    reason: "Reason",
    reasonWhyItMatters: "Why it matters",
    bodyPreview: "Body preview",
    htmlView: "HTML view",
    textView: "Text view",
    originalEmail: "Original email",
    noHtmlBody: "No HTML version was captured for this email.",
    noBodyPreview: "No body preview was captured for this email.",
    importanceScore: "Importance score",
    needsAction: "Needs action",
    confidence: "Confidence",
    uncertainty: "Uncertainty",
    noUncertainty: "No uncertainty note recorded.",
    viewEvidence: "View email",
    inspectRunTab: "Overview",
    inspectWorkflowTab: "Workflow",
    inspectEmailsTab: "Emails",
    inspectEvidenceTab: "Details",
    inspectReviewTab: "Review",
    inspectWorkspace: "Workspace",
    noEmailsTabTitle: "No emails available",
    noEmailsTabBody: "This saved summary does not include any emails to inspect yet.",
    noEvidenceTabTitle: "No email selected",
    noEvidenceTabBody: "Choose an email in the Emails tab to inspect its details here.",
    reviewPanel: "Review queue",
    reviewPanelCopy: "Confirm, reject, or correct extracted items and keep the saved run aligned with human review.",
    reviewPanelScope: "You are reviewing extracted items from emails, such as action items, deadlines, meetings, or financial obligations.",
    correctionHelp: "Only revise this single extracted card, not the whole daily summary.",
    reviewDecisionHelp: "Confirm keeps this extracted item. Reject removes it as a false positive. Correct keeps it, but with better content.",
    rejectHelp: "Reject if this extracted item should not exist at all.",
    correctHelp: "Correct if the item is useful, but its wording or details are wrong.",
    noExtractedItemsTitle: "No extracted items available",
    noExtractedItemsBody: "This run does not include reviewable extracted items yet.",
    reviewPending: "Pending",
    reviewConfirmed: "Confirmed",
    reviewRejected: "Rejected",
    reviewCorrected: "Corrected",
    confirm: "Confirm",
    reject: "Reject",
    correct: "Correct",
    saveCorrection: "Save correction",
    correctionLabel: "Corrected item",
    correctionPlaceholder: "Write how this extracted item should appear instead.",
    reviewerNote: "Reviewer note",
    reviewerNotePlaceholder: "Optional note about why you confirmed, rejected, or corrected this item.",
    reviewSaved: "Review update saved.",
    reviewSaveFailed: "Could not save the review update.",
    reviewStatus: "Review status",
    sourceEvidence: "Source evidence",
    extractedType: "Type",
    correctedValue: "Corrected item",
    noCorrectedValue: "No corrected item saved.",
    extractedTypeLabels: {
      action_item: "Action item",
      deadline: "Deadline",
      meeting: "Meeting",
      financial_obligation: "Financial obligation",
      follow_up: "Follow-up",
    },
    categoryLabels: {
      urgent: "Urgent",
      needs_reply: "Needs reply",
      meeting: "Meeting",
      finance: "Finance",
      info: "Info",
      low_priority: "Low priority",
    },
    heuristicOrFallback: "Heuristic or fallback",
    llmAssisted: "LLM-assisted",
    runModeMixed: (classification, summary) => `${classification} / ${summary}`,
  },
  de: {
    loadingKicker: "Laden",
    loadingTitle: "Laufartefakte werden geladen...",
    frontendKicker: "Frontend",
    loadErrorTitle: "Gespeicherte Läufe konnten nicht geladen werden",
    noDataKicker: "Noch keine Daten",
    noDataTitle: "Starte den Email-Agenten zuerst",
    noDataBody: "Gespeicherte Zusammenfassungen aus data/runs/ erscheinen hier automatisch.",
    runAgent: "Agent starten",
    runAgentTitle: "Neue Zusammenfassung erstellen",
    runAgentHint: "Wähle Quelle und Datum, um eine aktualisierte Zusammenfassung aus deinem Posteingang zu erzeugen.",
    runNow: "Zusammenfassung erstellen",
    runningRun: "Zusammenfassung wird erstellt...",
    runCompleted: (date) => `Zusammenfassung für ${date} abgeschlossen.`,
    runProvider: "Ausführen mit",
    runDate: "Datum",
    interfaceLanguage: "Sprache",
    briefMode: "Übersicht",
    inspectMode: "Inspektion",
    inspectTitle: "Technische Einsicht",
    openInspectMode: "Inspect-Modus öffnen",
    briefHeadline: "Dein Tag in E-Mails",
    currentRun: "Aktuelle Zusammenfassung",
    newRun: "Neue Zusammenfassung",
    launchHint: "Quelle und Datum wählen und dann eine neue Zusammenfassung erstellen.",
    signalLabel: "Tageszusammenfassung",
    runOverview: "Überblick",
    close: "Schließen",
    hideDetails: "Details ausblenden",
    showDetails: "Details anzeigen",
    savedRun: "Angezeigte Zusammenfassung",
    inspector: "Inspektor",
    technicalMetadata: "Technische Metadaten",
    inspectorPreview: "Öffne die Details für die vollständige technische Spur dieses Laufs.",
    provider: "Quelle",
    language: "Sprache",
    llm: "LLM",
    execution: "Ausführung",
    startedAt: "Gestartet",
    completedAt: "Beendet",
    workflowDuration: "Workflow-Dauer",
    inputTokens: "Input-Tokens",
    outputTokens: "Output-Tokens",
    totalTokens: "Gesamt-Tokens",
    estimatedCost: "Geschaetzte Kosten",
    emailCount: "E-Mail-Anzahl",
    emailCountFound: (count) => `${count} E-Mails an diesem Tag gefunden`,
    importantCount: "Wichtige E-Mails",
    llmClassification: "LLM-Klassifizierung",
    llmSummary: "LLM-Zusammenfassung",
    classificationRoute: "Klassifizierungsweg",
    summaryRoute: "Zusammenfassungsweg",
    lowConfidenceItems: "Unsichere Einträge",
    abstainedItems: "Enthaltungen",
    llmFallbacks: "LLM-Fallbacks",
    inboxFocus: "Posteingang",
    importantMessages: "Wichtige Nachrichten",
    noImportantMessages: "Für diese Zusammenfassung wurden keine wichtigen E-Mails erkannt.",
    actionBoard: "Nächste Schritte",
    nextSteps: "Nächste Schritte",
    noFollowup: "Für diese Zusammenfassung wurden keine Folgeaktionen erkannt.",
    deadlines: "Fristen",
    timeSensitiveItems: "Was bald ansteht",
    noDeadlines: "Für diese Zusammenfassung wurden keine anstehenden Fristen oder dringenden Punkte erkannt.",
    meetings: "Besprechungen",
    calendarSignals: "Termine und Einladungen",
    noMeetings: "Es wurden keine Termine oder Einladungen erkannt.",
    subscriptions: "Abos",
    recurringCharges: "Wiederkehrende Kosten",
    noSubscriptions: "Für diese Zusammenfassung wurden keine wahrscheinlichen Abos erkannt.",
    workflow: "Ablauf",
    systemPath: "Systempfad",
    hide: "Ausblenden",
    view: "Anzeigen",
    workflowSummary: "Eine kompakte Systemansicht ist verfügbar, wenn du den Ablauf genauer ansehen willst.",
    stepTimingSummary: "Jeder gespeicherte Lauf enthält jetzt Zeitstempel und Schrittdauern für eine klarere operative Spur.",
    stepCompletedInDetail: (duration) => `Abgeschlossen in ${duration}.`,
    usageRecordedDetail: (tokens, cost) =>
      tokens > 0 ? `${tokens} gesamte LLM-Tokens erfasst. Geschaetzte Kosten ${cost}.` : "Keine LLM-Token-Nutzung fuer diesen Lauf erfasst.",
    whyThisMatters: "Warum das wichtig ist",
    projectValue: "Projektwert",
    projectSummary: "Die Oberfläche bleibt bewusst produktnah, während die technische Sicht bei Bedarf verfügbar ist.",
    projectBullet1: "Echte Gmail-Läufe und gespeicherte Artefakte treiben die Oberfläche bereits an.",
    projectBullet2: "Die Produktansicht bleibt ruhig, während technische Metadaten gezielt verfügbar bleiben.",
    projectBullet3: "Als nächster Schritt bietet sich eine leichte API oder Live-Aktualisierung nach jedem Lauf an.",
    importantMails: "Wichtige E-Mails",
    subscriptionsStat: "Abos",
    deadlinesStat: "Fristen",
    meetingsStat: "Besprechungen",
    german: "Deutsch",
    english: "Englisch",
    unknown: "Unbekannt",
    yes: "Ja",
    no: "Nein",
    gmailLabel: "gmail",
    mockLabel: "mock",
    webdeLabel: "web.de",
    noPreview: "Keine Vorschau verfügbar.",
    savedSummary: "Gespeicherte Zusammenfassung",
    structuredExtraction: "Strukturierte Extraktion",
    artifactBackedUi: "Artefaktgestützte Oberfläche",
    guardrails: "Guardrails",
    nextStep: "Nächster Schritt",
    savedSummaryDetail: (date, count) => `summary.json für ${date} mit ${count} wichtigen E-Mails geladen.`,
    structuredExtractionDetail: (deadlines, meetings, subscriptions) =>
      `${deadlines} Fristsignale, ${meetings} Besprechungssignale und ${subscriptions} Abo-Signale als eigene Artefakte gespeichert.`,
    artifactBackedUiDetail: "Dieses Dashboard zeigt echte gespeicherte Ausgaben aus dem Python-Workflow.",
    guardrailsDetail: (fallbacks, abstained) =>
      fallbacks > 0
        ? `Guardrails haben ${fallbacks} unsichere Klassifizierungen durch sicherere Fallback-Logik ersetzt und ${abstained} Enthaltungen erfasst.`
        : "In diesem Lauf waren keine Fallbacks für unsichere Klassifizierungen nötig.",
    nextStepDetail: "Token-, Kosten- und Latenztelemetrie in die gespeicherten Laufmetadaten aufnehmen.",
    guardrailsBrief: (count) =>
      `Guardrails haben ${count} unsichere Klassifizierungen durch sicherere Fallback-Logik ersetzt.`,
    likelyRecurringFallback: "Wahrscheinliches Signal für ein wiederkehrendes Abo erkannt.",
    noMeetingDetails: "Keine weiteren Besprechungsdetails erkannt.",
    responseLikelyNeeded: "Antwort wahrscheinlich nötig",
    noDueHint: "Keine ausdrückliche Frist erkannt.",
    allEmails: "Alle E-Mails",
    runInbox: "E-Mails anzeigen",
    inspectEveryEmail: "Alle E-Mails aus dieser Zusammenfassung ansehen, auch Info- und weniger wichtige Nachrichten.",
    openAllEmails: "Alle E-Mails öffnen",
    emailDetail: "E-Mail-Detail",
    emailList: "E-Mails",
    openEmail: "E-Mail öffnen",
    receivedAt: "Empfangen",
    subject: "Betreff",
    senderLabel: "Absender",
    reason: "Begründung",
    reasonWhyItMatters: "Warum wichtig",
    bodyPreview: "Textvorschau",
    htmlView: "HTML-Ansicht",
    textView: "Textansicht",
    originalEmail: "Original-E-Mail",
    noHtmlBody: "Für diese E-Mail wurde keine HTML-Version erfasst.",
    noBodyPreview: "Für diese E-Mail wurde keine Textvorschau erfasst.",
    importanceScore: "Wichtigkeitswert",
    needsAction: "Aktion nötig",
    confidence: "Konfidenz",
    uncertainty: "Unsicherheit",
    noUncertainty: "Kein Unsicherheitshinweis erfasst.",
    viewEvidence: "E-Mail ansehen",
    inspectRunTab: "Überblick",
    inspectWorkflowTab: "Ablauf",
    inspectEmailsTab: "E-Mails",
    inspectEvidenceTab: "Details",
    inspectReviewTab: "Review",
    inspectWorkspace: "Arbeitsbereich",
    noEmailsTabTitle: "Keine E-Mails vorhanden",
    noEmailsTabBody: "Diese gespeicherte Zusammenfassung enthält derzeit keine E-Mails zur Prüfung.",
    noEvidenceTabTitle: "Keine E-Mail ausgewählt",
    noEvidenceTabBody: "Wähle im Tab E-Mails eine Nachricht aus, um hier ihre Details zu sehen.",
    reviewPanel: "Review-Warteschlange",
    reviewPanelCopy: "Bestätige, verwerfe oder korrigiere extrahierte Einträge und halte den gespeicherten Lauf mit menschlichem Review synchron.",
    reviewPanelScope: "Hier prüfst du extrahierte Einträge aus E-Mails, zum Beispiel Action Items, Fristen, Besprechungen oder finanzielle Hinweise.",
    correctionHelp: "Hier änderst du nur diese einzelne extrahierte Karte, nicht die gesamte Tageszusammenfassung.",
    reviewDecisionHelp: "Bestätigen behält diesen extrahierten Eintrag. Verwerfen markiert ihn als Fehlfund. Korrigieren behält ihn, aber mit besserem Inhalt.",
    rejectHelp: "Verwerfen, wenn dieser extrahierte Eintrag gar nicht hätte existieren sollen.",
    correctHelp: "Korrigieren, wenn der Eintrag sinnvoll ist, aber Text oder Details falsch sind.",
    noExtractedItemsTitle: "Keine extrahierten Einträge verfügbar",
    noExtractedItemsBody: "Dieser Lauf enthält noch keine reviewbaren extrahierten Einträge.",
    reviewPending: "Ausstehend",
    reviewConfirmed: "Bestätigt",
    reviewRejected: "Verworfen",
    reviewCorrected: "Korrigiert",
    confirm: "Bestätigen",
    reject: "Verwerfen",
    correct: "Korrigieren",
    saveCorrection: "Korrektur speichern",
    correctionLabel: "Korrigierter Eintrag",
    correctionPlaceholder: "Schreibe hier, wie dieser extrahierte Eintrag korrekt lauten sollte.",
    reviewerNote: "Review-Notiz",
    reviewerNotePlaceholder: "Optionale Notiz dazu, warum dieser Eintrag bestätigt, verworfen oder korrigiert wurde.",
    reviewSaved: "Review-Update gespeichert.",
    reviewSaveFailed: "Review-Update konnte nicht gespeichert werden.",
    reviewStatus: "Review-Status",
    sourceEvidence: "Quellbeleg",
    extractedType: "Typ",
    correctedValue: "Korrigierter Eintrag",
    noCorrectedValue: "Noch kein korrigierter Eintrag gespeichert.",
    extractedTypeLabels: {
      action_item: "Nächster Schritt",
      deadline: "Frist",
      meeting: "Besprechung",
      financial_obligation: "Finanzieller Punkt",
      follow_up: "Follow-up",
    },
    categoryLabels: {
      urgent: "Dringend",
      needs_reply: "Antwort nötig",
      meeting: "Besprechung",
      finance: "Finanzen",
      info: "Info",
      low_priority: "Niedrige Priorität",
    },
    heuristicOrFallback: "Heuristik oder Fallback",
    llmAssisted: "LLM-gestützt",
    runModeMixed: (classification, summary) => `${classification} / ${summary}`,
  },
};
